[package]
name = "tlsscanner"
version = "0.1.6"
edition = "2018"
authors = ["PinkP4nther <pinkp4nther@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.36"